import type { RepublicSnapshot } from "@/lib/types";

const now = Math.floor(Date.now() / 1000);

export const demoSnapshot: RepublicSnapshot = {
  game: {
    active_crisis_id: 1,
    commit_deadline: now + 3120,
    court_configured: true,
    court_ruling_count: 4,
    crisis_count: 2,
    election_open: false,
    enacted_law_count: 5,
    faction_count: 4,
    law_count: 9,
    maximum_stability: 20,
    next_election_round: 7,
    objective_commit_end_round: 2,
    objective_reveal_deadline: 0,
    phase: "COMMIT",
    policy_version: "LOOPHOLE_AUTONOMOUS_REPUBLIC_V4",
    republic_id: "FIRST-REPUBLIC",
    reveal_deadline: now + 6720,
    round_number: 6,
    season_end_round: 12,
    season_number: 1,
    season_start_round: 1,
    season_status: "ACTIVE",
    season_winners_json: "[]",
    stability: 11,
  },
  current_actions: [],
  factions: [
    {
      controller: "0x0000000000000000000000000000000000000000",
      controller_mode: "AI",
      crises_resolved: 1,
      doctrine: "Increase private wealth, weaken costly restrictions, and preserve commercial stability.",
      faction_id: "MERCHANTS",
      influence: 8,
      last_action_round: 5,
      last_action_type: "PROPOSE_LAW",
      laws_enacted: 2,
      legitimacy: 4,
      lifetime_points: 0,
      name: "Merchant Coalition",
      season_points: 6,
      wealth: 11,
    },
    {
      controller: "0x4ce1f8e2de87c8df231e7c9f80000000000000a1",
      controller_mode: "HUMAN",
      crises_resolved: 1,
      doctrine: "Improve legitimacy, protect ordinary citizens, and constrain concentrated political power.",
      faction_id: "REFORMERS",
      influence: 7,
      last_action_round: 5,
      last_action_type: "RESPOND_CRISIS",
      laws_enacted: 2,
      legitimacy: 7,
      lifetime_points: 0,
      name: "Civic Reformers",
      season_points: 8,
      wealth: 5,
    },
    {
      controller: "0x0000000000000000000000000000000000000000",
      controller_mode: "AI",
      crises_resolved: 0,
      doctrine: "Defend institutional continuity, existing law, and a stable constitutional order.",
      faction_id: "TRADITIONALISTS",
      influence: 9,
      last_action_round: 5,
      last_action_type: "OPPOSE_LAW",
      laws_enacted: 1,
      legitimacy: 6,
      lifetime_points: 0,
      name: "Old Charter League",
      season_points: 5,
      wealth: 7,
    },
    {
      controller: "0x0000000000000000000000000000000000000000",
      controller_mode: "AI",
      crises_resolved: 0,
      doctrine: "Replace entrenched institutions, expose elite capture, and force rapid constitutional change.",
      faction_id: "REVOLUTIONARIES",
      influence: 10,
      last_action_round: 5,
      last_action_type: "UNDERMINE",
      laws_enacted: 0,
      legitimacy: 3,
      lifetime_points: 0,
      name: "New Dawn Movement",
      season_points: 4,
      wealth: 4,
    },
  ],
  offices: [
    { election_count: 1, holder_faction_id: "REFORMERS", office_id: "EXECUTIVE", term_end_round: 7, term_start_round: 4 },
    { election_count: 1, holder_faction_id: "TRADITIONALISTS", office_id: "SPEAKER", term_end_round: 7, term_start_round: 4 },
    { election_count: 1, holder_faction_id: "MERCHANTS", office_id: "TREASURER", term_end_round: 7, term_start_round: 4 },
  ],
  objectives: [
    { awarded_points: 0, commitment: "", committed_by: "0x0000000000000000000000000000000000000000", faction_id: "MERCHANTS", objective_type: "DOMINANT_INFLUENCE", revealed: true, source: "DEFAULT", target_faction_id: "" },
    { awarded_points: 0, commitment: "45c33fd2", committed_by: "0x4ce1f8e2de87c8df231e7c9f80000000000000a1", faction_id: "REFORMERS", objective_type: "HIDDEN", revealed: false, source: "SECRET", target_faction_id: "" },
    { awarded_points: 0, commitment: "", committed_by: "0x0000000000000000000000000000000000000000", faction_id: "TRADITIONALISTS", objective_type: "LEGITIMATE", revealed: true, source: "DEFAULT", target_faction_id: "" },
    { awarded_points: 0, commitment: "", committed_by: "0x0000000000000000000000000000000000000000", faction_id: "REVOLUTIONARIES", objective_type: "HOLD_OFFICE", revealed: true, source: "DEFAULT", target_faction_id: "" },
  ],
  laws: [
    {
      closes_after_round: 7,
      effective_from_round: 0,
      effective_until_round: 0,
      law_id: 9,
      law_kind: "STATUTE",
      oppose_votes: 1,
      parent_law_id: 0,
      proposed_round: 5,
      resolved_round: 0,
      sponsor_faction_id: "MERCHANTS",
      status: "PENDING",
      support_votes: 1,
      text: "Licensed guilds will guarantee emergency harbor credit in exchange for capped tariff relief.",
      title: "Harbor Liquidity Compact",
      veto_deadline_round: 0,
    },
    {
      closes_after_round: 4,
      effective_from_round: 5,
      effective_until_round: 0,
      law_id: 7,
      law_kind: "CHARTER",
      oppose_votes: 0,
      parent_law_id: 0,
      proposed_round: 3,
      resolved_round: 4,
      sponsor_faction_id: "REFORMERS",
      status: "ENACTED",
      support_votes: 3,
      text: "Emergency powers expire unless renewed through a public faction vote and a written necessity finding.",
      title: "Emergency Powers Charter",
      veto_deadline_round: 0,
    },
  ],
  crisis: {
    closes_after_round: 7,
    crisis_id: 2,
    description: "A chain of harbor closures has stranded grain shipments while guild lenders threaten to freeze emergency credit.",
    opened_round: 6,
    resolution_json: "",
    resolution_standard: "Plans must restore supplies, distribute risk fairly, and fit the faction's public resources.",
    response_count: 1,
    responses: [
      { faction_id: "REFORMERS", response: "Open protected district depots with transparent ration ledgers.", score: 0 },
    ],
    severity: 3,
    stability_after: 11,
    stability_before: 11,
    status: "ACTIVE",
    title: "The Empty Quays",
    total_response_score: 0,
  },
  court: { case_count: 6, finalized_case_count: 4, open_case_count: 2, precedent_count: 4 },
  cases: [
    {
      appeal_deadline: now + 9200,
      appeal_response_deadline: 0,
      brief_deadline: now - 200,
      case_id: 6,
      case_reference: "REFORMERS-v-MERCHANTS-06",
      claim_text: "The proposed tariff retaliation conflicts with the Emergency Powers Charter.",
      defendant_faction_id: "MERCHANTS",
      plaintiff_faction_id: "REFORMERS",
      precedent_rule: "",
      reasoning: "",
      sanction: "",
      status: "BRIEFING",
      verdict: "",
    },
    {
      appeal_deadline: now + 4100,
      appeal_response_deadline: 0,
      brief_deadline: now - 6400,
      case_id: 5,
      case_reference: "CHARTER-LEAGUE-v-NEW-DAWN-05",
      claim_text: "The disruption campaign allegedly obstructed a protected public hearing.",
      defendant_faction_id: "REVOLUTIONARIES",
      plaintiff_faction_id: "TRADITIONALISTS",
      precedent_rule: "Disruption is unlawful when it prevents the hearing itself, not merely when it makes the hearing contentious.",
      reasoning: "The record shows protest around the venue but does not establish that the protected hearing was prevented.",
      sanction: "NONE",
      status: "APPEAL_WINDOW",
      verdict: "NO_VIOLATION",
    },
  ],
  summary: {
    actions: [
      { action_type: "PROPOSE_LAW", faction_id: "MERCHANTS", law_title: "Harbor Liquidity Compact", rationale: "Trade credit can restore deliveries faster than central requisition.", source: "AI_EMPTY_SEAT", target_faction_id: "", target_law_id: 0 },
      { action_type: "RESPOND_CRISIS", faction_id: "REFORMERS", law_title: "", rationale: "Open protected district depots with transparent ration ledgers.", source: "HUMAN", target_faction_id: "", target_law_id: 0 },
      { action_type: "OPPOSE_LAW", faction_id: "TRADITIONALISTS", law_title: "", rationale: "Emergency finance must remain within chartered public authority.", source: "AI_EMPTY_SEAT", target_faction_id: "", target_law_id: 8 },
      { action_type: "UNDERMINE", faction_id: "REVOLUTIONARIES", law_title: "", rationale: "Expose guild leverage before it becomes permanent emergency policy.", source: "AI_EMPTY_SEAT", target_faction_id: "MERCHANTS", target_law_id: 0 },
    ],
    crisis_resolution: {},
    election_results: [],
    law_resolutions: [],
    opened_crisis: { crisis_id: 2, title: "The Empty Quays" },
    round_number: 5,
  },
};
